services:
  clash-of-clans:
    image: node:20.0-bullseye-slim
    working_dir: /usr/src/app
    user: node
    command: |
      bash -c "
        npm install --no-audit
        npm run build
        npm run prod
      "
    ports:
      - '5050:5050'
    volumes:
      - ./:/usr/src/app
    networks:
      - zero-wars-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.labels.clash-of-clans == true

networks:
  zero-wars-network:
    driver: overlay
    attachable: true
