# Initializes a new nodejs project with docker

version: '3.7'
services:
  app:
    image: node:18.13.0
    user: 1000:1000
    container_name: zero-wars-api
    restart: unless-stopped
    working_dir: /usr/src/app
    command: |
      bash -c "
        npm install
        npm run build
        node dist/app.js
      "
    ports:
      - '5050:5050'
    volumes:
      - ./:/usr/src/app
    networks:
      - zero-wars-network

networks:
  zero-wars-network:
    driver: bridge
