# Initializes a new nodejs project with docker

version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: zero-wars-api
    container_name: zero-wars-api
    restart: unless-stopped
    command: sh -c "npm install --no-audit --no-fund && npm run start:dev"
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
