# Initializes a new nodejs project with docker

version: '3.7'
services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: zero-wars-api
    container_name: zero-wars-api
    restart: unless-stopped
    command: sh -c "npm install --no-audit --no-fund && npm run start:dev"
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
    networks:
      - zerowars

  db:
    image: mysql:8.3.0
    restart: unless-stopped
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zerowars
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: app
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 3
      interval: 5s
      start_period: 5s
    ports:
      - 3307:3306
    networks:
      - zerowars

networks:
  zerowars:
    driver: bridge
